[eurofuenmayor]
user = efuenmayor
group = efuenmayor

listen = /run/php/eurofuenmayor-php83.sock
listen.owner = efuenmayor
listen.group = efuenmayor
listen.mode = 0660

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

chdir = /home/efuenmayor/eurofuenmayor-portfolio
clear_env = no
